### ISSUE TITLE
Missing files for running the code

### ISSUE THREAD

**Issue by drixs2050** [LeonYang95/code-bot#2]
Hello,
I am trying to run your code for unit test generation (generate_prompts.py), I think the file opened at line 89:
`with open(
                    os.path.join(
                        code_base,
                        "data/d4j2_fix_info/" + bug_id + "/buggy_fix_info.json",
                    ),
                    "r",
                    encoding="utf-8",
                ) as info_reader:`
is missing in your data directory, is it possible for you to share this file?
Thanks a lot

**Comment by LeonYang95** [comment]
Hi,
Thanks for your issue, and sorry for the late response.
[d4j2_fix_info.zip](https://github.com/user-attachments/files/17824873/d4j2_fix_info.zip)
[source_data.jsonl.zip](https://github.com/user-attachments/files/17824876/source_data.jsonl.zip)

Here are some additional files that used in the project, you can find the missing files within. I will close this for now, if you have additional questions, feel free to reopen!

Thanks again!

Lin Yang
